# Generated by Django 5.2 on 2025-06-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField()),
                ('image', models.ImageField(upload_to='Service')),
                ('header', models.CharField(max_length=100)),
                ('description2', models.TextField()),
                ('point1', models.CharField(max_length=50)),
                ('point2', models.CharField(max_length=50)),
                ('point3', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
