# Generated by Django 5.2 on 2025-06-15 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_servicedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='index.service'),
            preserve_default=False,
        ),
    ]
