# Generated by Django 5.2 on 2025-06-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_servicedetails_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='title',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
