# Generated by Django 5.2 on 2025-06-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_servicedetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='point1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='point2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='point3',
            field=models.CharField(max_length=100),
        ),
    ]
