# Generated by Django 5.2 on 2025-06-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_servicedetails_point1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='Project-Detail')),
                ('image2', models.ImageField(upload_to='Project-Detail')),
                ('image3', models.ImageField(upload_to='Project-Detail')),
                ('image4', models.ImageField(upload_to='Project-Detail')),
                ('category', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('date', models.DateField()),
                ('header', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.project')),
            ],
        ),
    ]
