# Generated by Django 5.2 on 2025-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_project_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
    ]
